[project]
name = "weather-forecast-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plotly>=6.1.2",
    "streamlit>=1.46.0",
]
